#http://localhost:8080/actuator/info
info:
  app:
    name: spring boot microservice
    version: 1.0.0_RELEASE
    description: more details about sprint boot microservice
    contact-support: apisupportgroup@abc.com
  copyright: copyright (c) abc.com
  license: MIT
  tech-used:
    - name: java
      version: 11.x
    - name: spring-boot
      version: 2.x

#APP SPECIFIC CUSTOM PROPERTIES
app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.abc.controller
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    logging:
      enable: true
      url-patterns: /users/*,/posts/*
      requestIdParamName: reqId
server:
  port: 8080
logging:
  level:
    root: INFO
    com.abc.demo: DEBUG
  pattern:
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{REQUEST_ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
spring:
  banner:
    location: classpath:banner.txt
  jackson:
    serialization:
      indent_output: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: DB_USER_NAME
    password: ENCRYPTED_PASSWORD
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 10
  # Enabling H2 Console
  h2.console.enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
person:
  name: Ashish Kumar Lahoti
  occupation: blogger
  age: 34
  gpa: 3.5
  fav_num: 1e+10
  male: true
  birthday: 1986-08-22
  flaws: null
  hobbies:
    - bike riding
    - watching movies
    - online games
    - cooking
  movies: ["Dark Knight", "Spider Man", "Thor"]
  assets: {Car: 1, Bike: 2, Home: 1}
  size:
    t-shirt:
      us: XL
      uk: L
    shoes:
      us: 8.5
      uk: 6.5 
  friends:
    - name: "adam"
      age: 28
    - {name: "ben", age: 26}
    -
      name: "charlie"
      age: 40
  description: >
    Lorem ipsum dolor sit amet,
    consectetur adipiscing elit, sed
    do eiusmod tempor incididunt ut
    labore et dolore magna aliqua
  signature: |
    Thanks & Regards,
    Ashish Kumar Lahoti
    email - lahoti.ashish20@gmail.com
management.endpoints.web.exposure.include: info,health,release-notes
course1:
  title: "How to use Spring @Value annotation"
  duration: 30
  rating: 4.5
  page_views: 1e+10
  trending: true
  created_date: 2020-05-26
  tags: Spring, Spring Boot, Annotation
  

