#http://localhost:8080/actuator/info
info:
  app:
    name: spring boot microservice
    version: 1.0.0_RELEASE
    description: more details about sprint boot microservice
    contact-support: apisupportgroup@abc.com
  copyright: copyright (c) abc.com
  license: MIT
  tech-used:
    - name: java
      version: 11.x
    - name: spring-boot
      version: 2.x

#APP SPECIFIC CUSTOM PROPERTIES
app:
  name: spring boot application
server:
  port: 8080
logging:
  level:
    root: INFO
    com.abc.demo: DEBUG
  pattern:
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{REQUEST_ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
spring:
  banner:
    location: classpath:banner.txt
  jackson:
    serialization:
      indent_output: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: DB_USER_NAME
    password: ENCRYPTED_PASSWORD
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 10
  # Enabling H2 Console
  h2.console.enabled: true
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: TRACE