# INFO endpoint http://localhost:8080/actuator/info
info:
  app:
    title: spring boot microservice
    description: more details about sprint boot microservice
    version: 1.0.0_RELEASE
    base-package: com.example.demo
    contact-name: API Support Group
    contact-email: apisupportgroup@abc.com
    contact-url: http://example.com/team
    terms-of-service: http://example.com/terms/
    license-name: Apache 2.0
    license-url: http://www.apache.org/licenses/LICENSE-2.0.html
  copyright: copyright (c) abc.com
  tech-used:
    - name: java
      version: ${java.version}
    - name: spring-boot
      version: 2.x
management:
  endpoints:
    web:
      exposure:
        include: info,health,release-notes,custom-endpoint

custom.condition.enabled: false
another-custom.condition.enabled: false

# SERVER PROPERTIES
server:
  port: 8080
  jetty:
    connection-idle-timeout:
    max-http-form-post-size:
    accesslog:
      append: true
      enabled: true
      custom-format:
      file-date-format:
      filename:
      format:
      ignore-paths:
      retention-period: 31
    threads:
      acceptors:
      idle-timeout:
      max:
      max-queue-capacity:
      min:
      selectors:
  undertow:
    allow-encoded-slash: false # Whether the server should decode percent encoded slash characters. Enabling encoded slashes can have security implications due to different servers interpreting the slash differently. Only enable this if you have a legacy application that requires it.
    always-set-keep-alive: true # Whether the 'Connection: keep-alive' header should be added to all responses, even if not required by the HTTP specification.
    buffer-size: # Size of each buffer. The default is derived from the maximum amount of memory that is available to the JVM.
    decode-url: true # Whether the URL should be decoded. When disabled, percent-encoded characters in the URL will be left as-is.
    direct-buffers: # Whether to allocate buffers outside the Java heap. The default is derived from the maximum amount of memory that is available to the JVM.
    eager-filter-init: true # Whether servlet filters should be initialized on startup.
    max-cookies: 200 # Maximum number of cookies that are allowed. This limit exists to prevent hash collision based DOS attacks.
    max-headers: 12 # Maximum number of headers that are allowed. This limit exists to prevent hash collision based DOS attacks.
    max-parameters: # Maximum number of query or path parameters that are allowed. This limit exists to prevent hash collision based DOS attacks.
    max-http-post-size: -1B # Maximum size of the HTTP post content. When the value is -1, the default, the size is unlimited.
    no-request-timeout: # Amount of time a connection can sit idle without processing a request, before it is closed by the server.
    preserve-path-on-forward: false # Whether to preserve the path of a request when it is forwarded.
    url-charset: UTF-8 # Charset used to decode URLs
    accesslog:
      enabled: false # Whether to enable the access log
      dir: # Undertow access log directory
      pattern: common # Format pattern for access logs
      rotate: true # Whether to enable access log rotation
      prefix: access_log. # Log file name prefix.
      suffix: log # Log file name suffix
    threads:
      io: # Number of I/O threads to create for the worker. The default is derived from the number of available processors.
      worker: # Number of worker threads. The default is 8 times the number of I/O threads.

# LOGGING PROPERTIES
logging:
  level:
    root: INFO
    com.example.demo: DEBUG
  pattern:
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{REQUEST_ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# OPENFEIGN PROPERTIES
feign.httpclient.enabled: true

# SPRING PROPERTIES
spring:
  banner:
    location: classpath:banner.txt
  jackson:
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false

# PERSON CONFIG PROPERTIES
person:
  name: Ashish Kumar Lahoti
  occupation: blogger
  age: 34
  gpa: 3.5
  fav_num: 1e+10
  male: true
  birthday: 1986-08-22
  flaws: null
  hobbies:
    - bike riding
    - watching movies
    - online games
    - cooking
  movies: ["Dark Knight", "Spider Man", "Thor"]
  assets: {Car: 1, Bike: 2, Home: 1}
  size:
    t-shirt:
      us: XL
      uk: L
    shoes:
      us: 8.5
      uk: 6.5 
  friends:
    - name: "adam"
      age: 28
    - {name: "ben", age: 26}
    -
      name: "charlie"
      age: 40
  description: >
    Lorem ipsum dolor sit amet,
    consectetur adipiscing elit, sed
    do eiusmod tempor incididunt ut
    labore et dolore magna aliqua
  signature: |
    Thanks & Regards,
    Ashish Kumar Lahoti
    email - lahoti.ashish20@gmail.com
app:
  config:
    keyword1: value1
    keyword2: value2
    keyword3: value3

  

